# Change these first
owner: streamonaire # Your GitHub organization or username, where this repository lives
repo: upptime-status-reports # The name of this repository

sites:
  - name: Main Site
    url: https://streamonaire.com
  - name: Beta Site
    url: https://beta.streamonaire.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.streamonaire.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/streamonaire/upptime-status-reports/master/assets/streamonaire-logo.svg
  name: Streamonaire
  introTitle: "**Streamonaire** is a trivia game, made entirely for streamers."
  introMessage: This is the official status page for Streamonaire. Note it is a work in progress, and may change at any time.
  navbar:
    - title: Status
      href: /
    - title: Streamonaire
      href: https://streamonaire.com
    - title: Beta
      href: https://beta.streamonaire.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
